In [1]:
# Ramon Montoya
# Assignment 2A Practicing Python Programming

# Importing the pandas library 
import pandas as pd

# Loading the grocery dataset. 
df = pd.read_csv('grocery.csv')

# Checking the dataframe. 
print(df.head())

# Show the top 10 rows from grocery. 
df.head(10)

# Show the last 10 rows from grocery. 
df.tail(10)

# Summarize the dataframe. 
df.info()

                tem               Category Refrigeration Required  \
0    Macadamia Nuts          Miscellaneous                     No
1  Brussels Sprouts  Fruits and Vegetables                    Yes
2            Coffee              Beverages                     No
3       Maple Syrup      Snacks and Sweets                    Yes
4          Flaxseed          Miscellaneous                     No

   Weight (lbs)   Price Country of Origin  Manufacturer
0           1.0  $7.00      United States       Nut Co.
1           1.0  $2.00           Colombia    Veggie Co.
2           1.0  $5.00             Brazil  Beverage Co.
3           1.0  $4.00             Canada    Snacks Co.
4           1.0  $4.00             Canada      Seed Co.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tem                     184 non-null    object
 1   Category                184 non-null    object
 2   Refrigeration Required  184 non-null    object
 3   Weight (lbs)            184 non-null    float64
 4   Price                   184 non-null    object
 5   Country of Origin       184 non-null    object
 6   Manufacturer            183 non-null    object
dtypes: float64(1), object(6)
memory usage: 10.2+ KB

In [2]:
# Checking the dataframe. 
print(df.head())

                tem               Category Refrigeration Required  \
0    Macadamia Nuts          Miscellaneous                     No
1  Brussels Sprouts  Fruits and Vegetables                    Yes
2            Coffee              Beverages                     No
3       Maple Syrup      Snacks and Sweets                    Yes
4          Flaxseed          Miscellaneous                     No

   Weight (lbs)   Price Country of Origin  Manufacturer
0           1.0  $7.00      United States       Nut Co.
1           1.0  $2.00           Colombia    Veggie Co.
2           1.0  $5.00             Brazil  Beverage Co.
3           1.0  $4.00             Canada    Snacks Co.
4           1.0  $4.00             Canada      Seed Co.

In [3]:
# Show the top 10 rows from grocery. 
df.head(10)

,tem,Category,Refrigeration Required,Weight (lbs),Price,Country of Origin,Manufacturer
0,Macadamia Nuts,Miscellaneous,No,1.00,$7.00,United States,Nut Co.
1,Brussels Sprouts,Fruits and Vegetables,Yes,1.00,$2.00,Colombia,Veggie Co.
2,Coffee,Beverages,No,1.00,$5.00,Brazil,Beverage Co.
3,Maple Syrup,Snacks and Sweets,Yes,1.00,$4.00,Canada,Snacks Co.
4,Flaxseed,Miscellaneous,No,1.00,$4.00,Canada,Seed Co.
5,Tofu,Miscellaneous,Yes,1.00,$3.00,United States,NaN
6,Bok Choy,Fruits and Vegetables,Yes,1.00,$1.20,United States,Veggie Co.
7,Cabbage,Fruits and Vegetables,Yes,1.00,$1.00,United States,Veggie Co.
8,Chives,Fruits and Vegetables,Yes,0.10,$1.00,United States,Herb Co.
9,Garlic,Fruits and Vegetables,No,0.25,$1.00,United States,Veggie Co.

In [4]:
# Show the last 10 rows from grocery. 
df.tail(10)

,tem,Category,Refrigeration Required,Weight (lbs),Price,Country of Origin,Manufacturer
174,Veggie Burgers,Frozen Foods,Yes,1.0,$3.00,United States,Frozen Co.
175,Walnuts,Miscellaneous,No,1.0,$5.00,United States,Nut Co.
176,Watercress,Fruits and Vegetables,Yes,0.5,$1.50,United States,Veggie Co.
177,Wheat Bread,Bakery and Grains,"No (until opened, then yes)",1.0,$2.00,United States,Bakery Co.
178,White Beans,Canned and Packaged Goods,No,1.0,$1.50,United States,Bean Co.
179,White Rice,Canned and Packaged Goods,No,1.0,$1.00,United States,Rice Co.
180,Whole Wheat Flour,Bakery and Grains,No,1.0,$2.00,United States,Bakery Co.
181,Wild Rice,Canned and Packaged Goods,No,1.0,$5.00,United States,Rice Co.
182,Yogurt-covered Pretzels,Snacks and Sweets,No,0.5,$2.50,United States,Snacks Co.
183,Zucchini,Fruits and Vegetables,Yes,1.0,$1.20,United States,Veggie Co.

In [5]:
# Summarize the dataframe. 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tem                     184 non-null    object
 1   Category                184 non-null    object
 2   Refrigeration Required  184 non-null    object
 3   Weight (lbs)            184 non-null    float64
 4   Price                   184 non-null    object
 5   Country of Origin       184 non-null    object
 6   Manufacturer            183 non-null    object
dtypes: float64(1), object(6)
memory usage: 10.2+ KB